// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg_AKhzEDUBsrBd5p6A-kRzdwBSivakcY',
    appId: '1:413226749154:web:28645def39fd1130d162bb',
    messagingSenderId: '413226749154',
    projectId: 'roombookingapp-da5df',
    authDomain: 'roombookingapp-da5df.firebaseapp.com',
    storageBucket: 'roombookingapp-da5df.appspot.com',
    measurementId: 'G-KVKL25N0EB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPFpfrDY6zfe8qapRsuEp1dZXDzDKRcPA',
    appId: '1:413226749154:android:1016805492d006c6d162bb',
    messagingSenderId: '413226749154',
    projectId: 'roombookingapp-da5df',
    storageBucket: 'roombookingapp-da5df.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg_AKhzEDUBsrBd5p6A-kRzdwBSivakcY',
    appId: '1:413226749154:web:b3622da182a6e157d162bb',
    messagingSenderId: '413226749154',
    projectId: 'roombookingapp-da5df',
    authDomain: 'roombookingapp-da5df.firebaseapp.com',
    storageBucket: 'roombookingapp-da5df.appspot.com',
    measurementId: 'G-7557H1HTDJ',
  );
}
