// import 'package:cloud_firestore/cloud_firestore.dart';

// class FormUtils {
//   // Function to get Firebase autogenerated ID
//   Future<String> getFirebaseAutoId() async {
//     CollectionReference collectionRef =
//         FirebaseFirestore.instance.collection('unauthorised_hotel');
//     DocumentReference docRef = collectionRef.doc();
//     return docRef.id; // Return the auto-generated ID
//   }

//   // Function to store data in Firebase
//   Future<void> storeData(Map<String, dynamic> data) async {
//     CollectionReference collectionRef =
//         FirebaseFirestore.instance.collection('unauthorised_hotel');
//     await collectionRef.add(data); // Add data to the Firestore collection
//   }
// }
